#!groovy

properties([disableConcurrentBuilds()])
def agentLabel
echo env.GIT_BRANCH
if (env.GIT_BRANCH == "release"){
    agentLabel = "prod"
} else {
    agentLabel = "phys"
}

pipeline {
    agent { label agentLabel }
    options {
        timestamps()
    }
    stages {
        stage("Echo server"){
            steps {
                echo agentLabel
            }
        }
        stage("Say Hello"){
            steps {
                echo 'Hello World'
            }
        }
    }
}
