#!groovy

properties([disableConcurrentBuilds()])

pipeline {
    agent any 
    options {
        buildDiscarder(logRotator(numToKeepStr: '5', artifactNumToKeepStr: '5'))
        timestamps()
    }
    stages {
        stage("Say Hello"){
            steps {
                sh "echo 'Hello World'"
            }
        }
    }
}
